# Permalinks
permalink:        pretty

# Setup
title:            "wiki âœ"
tagline:          'My personal wiki'
description:      'A mixture of code, recipes and other stuff ...'
url:              http://frostrubin.github.io
baseurl:          /

author:
  name:           'Bernhard Seeger'

paginate:         5

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/frostrubin/frostrubin.github.io
